name: Documentation tests

on:
  pull_request:
    branches: [main]
    paths:
      - "docs/how-to/**"
      - "docs/tutorials/**"
      - "tests/spread/documentation/**"
      - "app/**"
      - "artifacts.yaml"
      - "concierge-lxd.yaml"
      - "spread.yaml"
      - ".github/workflows/documentation-tests.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation-tests:
    uses: canonical/charm-ci/.github/workflows/doc-test.yml@0eef5b8cbef3ee74907850f790cab64bcf0499e5 # v1.0.0
    permissions:
      contents: read
      actions: read
    with:
      working-directory: .
      spread-jobs-include: "docs-ci:*"
    secrets: inherit
