name: Tests

on:
  pull_request:

jobs:
  test:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    with:
      working-directory: ./app/charm/
      charm-directory: .
      runs-on-base: ubuntu-24.04
      python-version: "3.12"
      with-uv: true
    secrets: inherit
